"""
validate_sources.py — Check all source URLs and generate fix SQL for broken ones.
Run inside Docker: docker exec agrisathi-pipeline-api-1 python scripts/validate_sources.py
"""
import httpx
from sqlalchemy import create_engine, text
from core.config import settings

ALTERNATIVES = {
    "mpkv_cotton_package_of_practices": [
        "https://mpkv.ac.in/Package-of-Practices",
        "https://icar.org.in/content/cotton-production-technology",
    ],
    "mpkv_soybean_package_of_practices": [
        "https://mpkv.ac.in/Package-of-Practices",
        "https://icar.org.in/content/soybean",
    ],
    "mahaagri_crop_advisory": [
        "https://mahapocra.gov.in/crop-advisory",
        "https://krishi.maharashtra.gov.in",
    ],
    "pmfby_insurance_guidelines": [
        "https://pmfby.gov.in/pdf/PMFBY_Operational_Guidelines_2.0.pdf",
        "https://agricoop.nic.in/sites/default/files/PMFBY_OG.pdf",
    ],
    "nhrdf_onion_advisory": [
        "https://nhrdf.com/en-us/Advisories",
        "https://nhrdf.com",
    ],
    "imd_agromet_advisory": [
        "https://internal.imd.gov.in/pages/agromet_main.php",
        "https://imdpune.gov.in/Agri/index.html",
    ],
    "icar_crop_advisory_pdf": [
        "https://icar.org.in/sites/default/files/ICAR-AR-2023-24-Eng.pdf",
    ],
    "ncipm_pest_alerts": [
        "https://ncipm.icar.gov.in/index.php/pest-surveillance",
    ],
}

TIMEOUT = 10


def check_url(url: str) -> tuple[str, int | str]:
    """Returns (status, code_or_reason)."""
    try:
        r = httpx.head(url, timeout=TIMEOUT, follow_redirects=True,
                       headers={"User-Agent": "AgriSathi-Validator/1.0"})
        if r.status_code < 400:
            return "OK", r.status_code
        # Some servers reject HEAD — try GET with stream
        r2 = httpx.get(url, timeout=TIMEOUT, follow_redirects=True,
                       headers={"User-Agent": "AgriSathi-Validator/1.0"})
        if r2.status_code < 400:
            return "OK", r2.status_code
        return "FAIL", r2.status_code
    except httpx.TimeoutException:
        return "FAIL", "timeout"
    except httpx.RequestError as e:
        return "FAIL", str(e)[:40]


def find_best_replacement(name: str) -> str | None:
    alts = ALTERNATIVES.get(name, [])
    for url in alts:
        status, code = check_url(url)
        if status == "OK":
            return url
    return alts[0] if alts else None


def main():
    engine = create_engine(settings.DATABASE_URL)
    with engine.connect() as conn:
        rows = conn.execute(
            text("SELECT name, url FROM data_sources ORDER BY name")
        ).fetchall()

    print(f"\n{'─'*80}")
    print(f"{'STATUS':<6} {'CODE':<10} {'SOURCE NAME':<38} {'URL'}")
    print(f"{'─'*80}")

    ok_count = 0
    fail_count = 0
    failed_sources = []

    for name, url in rows:
        status, code = check_url(url)
        tag = "OK  " if status == "OK" else "FAIL"
        print(f"{tag}  {str(code):<10} {name:<38} {url}")
        if status == "OK":
            ok_count += 1
        else:
            fail_count += 1
            failed_sources.append((name, url, code))

    print(f"{'─'*80}")
    print(f"\nSummary: {ok_count} sources OK, {fail_count} sources FAILED\n")

    if not failed_sources:
        print("All sources are reachable. No fix SQL needed.")
        return

    print("Suggested replacements for failed sources:")
    print(f"{'─'*60}")
    sql_lines = []
    for name, original_url, code in failed_sources:
        replacement = find_best_replacement(name)
        if replacement:
            print(f"  {name}")
            print(f"    Original : {original_url}")
            print(f"    Replace  : {replacement}")
            print()
            sql_lines.append(
                f"UPDATE data_sources SET url = '{replacement}', updated_at = NOW() "
                f"WHERE name = '{name}';"
            )
        else:
            print(f"  {name} — no known alternative available")
            print()

    sql_path = "/app/scripts/fix_broken_sources.sql"
    with open(sql_path, "w") as f:
        f.write("-- Auto-generated by validate_sources.py\n")
        f.write("-- Run: psql -U agrisathi -d agrisathi_pipeline -f scripts/fix_broken_sources.sql\n\n")
        f.write("\n".join(sql_lines) + "\n")
    print(f"Fix SQL written to: {sql_path}")


if __name__ == "__main__":
    main()
